services:
  db:
    image: postgres:15
    container_name: managements_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: managements_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # ✅ Con esto podés conectarte desde TablePlus

  app:
    build: .
    container_name: managements_app_front
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/managements_app_db
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma generate &&
             npm run dev"

volumes:
  postgres_data:
