import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google";
import { Oswald } from "next/font/google";
import "./globals.css";

// const roboto = Roboto({
//   weight: ["100", "300", "400", "700", "900"],
//   subsets: ["latin"],
// });

const oswald = Oswald({
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${oswald.className} antialiased`}>{children}</body>
    </html>
  );
}
